local seraphine = {}
seraphine.camlock = loadstring(game:HttpGet("https://raw.githubusercontent.com/Czzzqix/seraphine-private/refs/heads/main/modules/camlock.luau"))()


--==========================================
seraphine.camlock.settings.Enabled = true
seraphine.camlock.settings.ShowFOV = true
seraphine.camlock.settings.FOV = 150
seraphine.camlock.settings.Mode = "Toggle"
seraphine.camlock.settings.Prediction = 0.14
seraphine.camlock.settings.FOVColor = Color3.fromRGB(0, 255, 0)
--==========================================
